{
  "openapi": "3.0.0",
  "info": {
    "title": "Magacare",
    "description": "API para controle de lista de desejos de ecommerce.",
    "termsOfService": "www.google.com.br",
    "contacts": {
      "email": "email@email.com"
    },
    "version": "1.0.0"
  },
  "servers": [{
    "url": "https://magacare.herokuapp.com",
    "description": "API teste"
  }],
  "tags": [
    {
      "name": "Authentication",
      "description": "Session to get the authentication token."
    },
    {
      "name": "Clients",
      "description": "Routes of clients module."
    },
    {
      "name": "Products",
      "description": "Route of products module."
    },
    {
      "name": "Wishlists",
      "description": "Route of wishlists module."
    }
  ],
  "paths": {
    "/session": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Get the authentication token.",
        "description": "Session to give information and receive the authentication token.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Account unauthorized OR some information is wrong."
          },
          "404": {
            "description": "Error authenticating account."
          }
        }
      }
    },
    "/clients": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Create new client",
        "description": "Route responsable to create new clients.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "example": {
                "fullName": "Malu Campos",
                "email": "marialuisa@email.com.br",
                "birthDate": "01/16/2001",
                "cpf": "12345678901",
                "phoneNumber": "81998929985",
                "postalCode": "50070123",
                "gender": "Mulher Cis",
                "password": "testeteste123"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Client created."
          },
          "400": {
            "description": "The email or the CPF is already in use."
          },
          "500": {
            "description": "Error."
          }
        }
      },
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search all clients",
        "description": "Route responsable to search all clients.",
        "security": [{
          "bearerAuth": []
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding clients."
          }
        }
      }
    },
    "/clients/{clientId}": {
      "put": {
        "tags": [
          "Clients"
        ],
        "summary": "Update client",
        "description": "Route that updates clients and it is not possible to update with an Email or with an CPF that already exists.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "clientId",
          "type": "string",
          "required": "true",
          "description": "Client's id to update."
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Update client"
              },
              "example": {
                "fullName": "Maria Luisa Campos",
                "email": "marialuisa@email.com.br",
                "birthDate": "01/16/2001",
                "cpf": "12345678901",
                "phoneNumber": "81998929985",
                "postalCode": "50070123",
                "gender": "Mulher Cis",
                "oldPassword": "teste123",
                "password": "testeteste123",
                "confirmPassword": "testeteste123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Client updated."
          },
          "400": {
            "description": "The email or the CPF is already in use."
          },
          "401": {
            "description": "Some information is wrong."
          },
          "404": {
            "description": "Error."
          }
        }
      },
      "delete": {
        "tags": ["Clients"],
        "summary": "Delete clients by ID.",
        "description": "Route responsible to delete clients. If the client has a wishlist, it's also deleted.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "id",
          "type": "string",
          "required": "true",
          "description": "Client's id to delete."
        }],
        "responses": {
          "200": {
            "description": "Client deleted."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "/clients/wishlists/{clientId}": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client's wishlists ids.",
        "description": "Route responsible to search the client's wishlists ids by his id.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "clientId",
          "type": "string",
          "required": "true",
          "description": "Client's id to search wishlists"
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "/clients/id/{clientId}": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client by ID.",
        "description": "Route responsable to search client by his ID.",
        "parameters": {
          "in": "path",
          "name": "clientId",
          "type": "string",
          "required": "true",
          "description": "Client's id to search its informations."
        },
        "security": [{
          "bearerAuth": []
        }],
        "responses": {
          "200": {
            "description": "OK.",
            "schema": {
              "$ref":"#/components/schemas/Create client",
              "example": {
                "fullname": "Maria Luisa Campos",
                "email": "marialuisa@email.com.br",
                "birthdate": "01/16/2001",
                "cpf": "12345678901",
                "phonenumber": "81998929985",
                "postalcode": "50070123",
                "gender": "Mulher Cis",
                "password": "testeteste123"
              }
            }
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "/clients/email": {
      "get": {
        "tags": ["Clients"],
        "summary": "Search clients by email",
        "description": "Route that search clients by his email by query params.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "query",
          "name": "email",
          "type": "string",
          "required": "true",
          "description": "Client's email to get his informations. "
        }],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Error finding client by email."
          }
        }
      }
    },
    "/clients/search": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client with filter and pagination.",
        "description": "Route responsable to search client by filter (name, id or gender) and pagination, where you can choose the page and the limit of clients in each page.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [
          {
            "in": "query",
            "name": "searchBy",
            "type": "string",
            "required": "true",
            "description": "Decides the type of filter you want to use. It can be the client's id, name or gender."
          },
          {
            "in": "query",
            "name": "filter",
            "type": "string",
            "required": "true",
            "description": "Filter used to search the client."
          },
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "required": "false",
            "description": "Search's page. The default page is 1."
          },
          {
            "in": "query",
            "name": "limit",
            "type": "integer",
            "required": "false",
            "description": "How many clients showing in each page. The default quantity is 5."
          }
        ],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },

    "/products": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Create new product",
        "description": "Route responsible to create new products.",
        "security": [{
          "bearerAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Product"
              },
              "example": {
                "code": "549595295949",
                "name": "Água Micelar",
                "description": "Limpeza da pele de forma delicada",
                "volume": "150 ml",
                "recommendation": "todos os tipos de pele"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Product registered."
          },
          "400": {
            "description": "This name/code already exists."
          },
          "404": {
            "description": "Error creating product."
          }
        }
      },
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Search all products",
        "description": "Route responsable to search all products.",
        "security": [{
          "bearerAuth": []
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding products."
          }
        }
      }
    },
    "/products/{productCode}": {
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Update product",
        "description": "Route that updates products and it is not possible to update if the name already exists. The code cannot be changed.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "productCode",
          "type": "string",
          "required": "true",
          "description": "Code of the product that will be updated."
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Product"
              },
              "example": {
                "code": "549595295949",
                "name": "Hidratante Karite",
                "description": "Hidratante facial com manteiga de Karite",
                "volume": "120 ml",
                "recommendation": "pele seca"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Product updated."
          },
          "400": {
            "description": "This name already exists."
          },          
          "404": {
            "description": "Error updating product."
          }
        }
      },
      "delete": {
        "tags": ["Products"],
        "summary": "Delete products by code.",
        "description": "Route responsable to delete products. Product cannot be deleted if it's on a wishlist.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "code",
          "type": "string",
          "required": "true",
          "description": "Product's code to delete."
        }],
        "responses": {
          "200": {
            "description": "Product deleted."
          },
          "401": {
            "description": "Product cannot be deleted as it is on a wish list."
          },
          "404": {
            "description": "Error deleting product."
          }
        }
      }
    },
    "/products/wishlists/{productCode}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Search wishlists by product's code.",
        "description": "Route responsible to search wishlists by product's code.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "productCode",
          "type": "string",
          "required": "true",
          "description": "Product's code to search wishlists that has it."
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "400": {
            "description": "No product found."
          },
          "404": {
            "description": "Error finding product."
          }
        }
      }
    },
    "/products/code/{productCode}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Search product by code.",
        "description": "Route responsible to search a product by code.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "productCode",
          "type": "string",
          "required": "true",
          "description": "Product's code to search it."
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding product."
          }
        }
      }
    },
    "/products/search": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Search product with filter and pagination.",
        "description": "Route responsible to search product by filter and pagination, where you can choose the page and the limit of products in each page.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [
          {
            "in": "query",
            "name": "searchBy",
            "type": "string",
            "required": "true",
            "description": "Decides the type of filter you want to use. It can be the product's name, code or recommendation."
          },
          {
            "in": "query",
            "name": "filter",
            "type": "string",
            "required": "true",
            "description": "Filter used to search the product."
          },
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "required": "false",
            "description": "Search's page. The default page is 1."
          },
          {
            "in": "query",
            "name": "limit",
            "type": "integer",
            "required": "false",
            "description": "How many products showing in each page. The default quantity is 5."
          }
        ],
        "responses": {
          "200": {
            "description": "OK."
          },
          "400": {
            "description": "No product found."
          },
          "404": {
            "description": "Error finding products."
          }
        }
      }
    },

    "/wishlists": {
      "post": {
        "tags": [
          "Wishlists"
        ],
        "summary": "Create new wishlist",
        "description": "Route responsible to create new wishlists.",
        "security": [{
          "bearerAuth": []
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Wishlist"
              },
              "example": {
                "title": "Lista de Natal",
                "client": "628e97add291a4d768eb119e",
                "product": ["549595295949"],
                "createdAt": "2022-05-25T23:53:01.428Z"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Wishlist registered."
          },
          "400": {
            "description": "The wish list should have one product at least OR The client does not exist OR You cannot add duplicate products OR You cannot add product not existent"
          },
          "404": {
            "description": "Error creating wishlist."
          }
        }
      },
      "get": {
        "tags": [
          "Wishlists"
        ],
        "summary": "Search all wishlists",
        "description": "Route responsable to search all wishlists.",
        "security": [{
          "bearerAuth": []
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding wishlists."
          }
        }
      }
    },
    "/wishlists/{wishlistId}": {
      "put": {
        "tags": [ "Wishlists" ],
        "summary": "Update wishlist",
        "description": "Route that updates wishlists. It can't be empty, have duplicate products or change client.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "wishlistId",
          "type": "string",
          "required": "true",
          "description": "Wishlist update."
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Wishlist"
              },
              "example": {
                "title": "Lista de Pascoa",
                "client": "628e97add291a4d768eb119e",
                "product": "549595295949",
                "createdAt": "2022-05-25T23:53:01.428Z"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Wishlist updated."
          },
          "400": {
            "description": "The wish list update should have one product at least OR You cannot add duplicate products OR You cannot add products not existents"
          },       
          "404": {
            "description": "Error."
          }
        }
      },
      "delete": {
        "tags": ["Wishlists"],
        "summary": "Delete wishlists by id.",
        "description": "Route responsible to delete wishlists.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "id",
          "type": "string",
          "required": "true",
          "description": "Wishlist's id to delete."
        }],
        "responses": {
          "200": {
            "description": "Wishlist deleted."
          },
          "404": {
            "description": "Error deleting wishlist."
          }
        }
      }
    },
    "/wishlists/product/{wishlistId}": {
      "delete": {
        "tags": [ "Wishlists" ],
        "summary": "Delete product on wishlist.",
        "description": "Route that deletes products on a wishlist. It can't delete if there is only one product.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "wishlistId",
          "type": "string",
          "required": "true",
          "description": "Wishlist's id where the product will be deleted."
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "product": "888888"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Product deleted."
          },
          "400": {
            "description": "Wishlist not found."
          },       
          "404": {
            "description": "Error deleting product."
          }
        }
      }
    },
    "/wishlists/search": {
      "get": {
        "tags": [ "Wishlists" ],
        "summary": "Search wishlist with filter and pagination.",
        "description": "Route responsible to search wishlist by filter and pagination, where you can choose the page and the limit of wishlists in each page.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [
          {
            "in": "query",
            "name": "searchBy",
            "type": "string",
            "required": "true",
            "description": "Decides the type of filter you want to use. It can be the wishlist's title, id or product."
          },
          {
            "in": "query",
            "name": "filter",
            "type": "string",
            "required": "true",
            "description": "Filter used to search the wishlist."
          },
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "required": "false",
            "description": "Search's page. The default page is 1."
          },
          {
            "in": "query",
            "name": "limit",
            "type": "integer",
            "required": "false",
            "description": "How many wishlists showing in each page. The default quantity is 5."
          }
        ],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding wishlist."
          }
        }
      } 
    },
    "/wishlists/id/{wishlistId}": {
      "get": {
        "tags": [
          "Wishlists"
        ],
        "summary": "Search wishlist by id.",
        "description": "Route responsible to search a wishlist by id.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "wishlistId",
          "type": "string",
          "required": "true",
          "description": "Wishlist's id to search it."
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding wishlist."
          }
        }
      }
    },
    "/wishlists/client/{clientId}": {
      "get": {
        "tags": [
          "Wishlists"
        ],
        "summary": "Search wishlist by client's id.",
        "description": "Route responsible to search wishlists by client's id.",
        "security": [{
          "bearerAuth": []
        }],
        "parameters": [{
          "in": "path",
          "name": "clientId",
          "type": "string",
          "required": "true",
          "description": "Client's id to search wishlists."
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error finding wishlist."
          }
        }
      }
    }





  },
  


  "components": {
    "schemas": {
      "Client": {
        "type": "object",
        "properties": {
          "fullname": {
            "type": "string",
            "required": "true"
          },
          "email": {
            "type": "string",
            "required": "true",
            "lowercase": "true",
            "unique": "true"
          },
          "birthdate": {
            "type": "date",
            "required": "true"
          },
          "cpf": {
            "type": "string",
            "required": "true",
            "unique": "true"
          },
          "phonenumber": {
            "type": "string",
            "required": "true"
          },
          "postalcode": {
            "type": "string",
            "required": "true"
          },
          "gender": {
            "type": "string",
            "default": "prefiro não responder",
            "required": "true"
          },
          "password": {
            "type": "string",
            "required": "true"
          }
        }
      },
      "Update client": {
        "type": "object",
        "properties": {
          "fullName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "lowercase": "true"
          },
          "birthDate": {
            "type": "date"
          },
          "cpf": {
            "type": "string"
          },
          "phoneNumber": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "oldPassword": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "confirmPassword": {
            "type": "string"
          }
        }
      },
      "Product": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "required": true,
            "unique": true
          },
          "name": {
            "type": "string",
            "required": true,
            "unique": true
          },
          "description": {
            "type": "string",
            "required": true
          },
          "volume": {
            "type": "string",
            "required": true
          },
          "recommendation": {
            "type": "string",
            "required": true
          }
        }
      },
      "Wishlist": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "required": "true"
          },
          "client": {
            "type": "objectid",
            "ref": "clients"
          },
          "product": {
            "type": "string"
          },
          "createdAt": {
            "type": "date",
            "default": "timestamp"
          } 
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "responses": {
      "UnauthorizedError": {
        "description": "Access token is missing or invalid."
      }
    }
  }
}

